.github/workflows/pr.yml
CI is failing for macOS otherwise.
There's an additional failure hiding behind this one; looking at that now.
=> Only install debian deps on ubuntu runner

bb-imager-gui/src/helpers.rs, bb-imager-gui/src/pages/destination_selection.rs
Admittedly, most likely everything will be easily measured in GB and TB, but in cases where smaller volumes show up it may be nice to avoid a small decimal number.
Was originally motivated by running this on a machine with a >1TB disk showing up -- not that'd you'd actually want to write there!
=> Format disk sizes in terms other than GB

bb-flasher-sd/src/lib.rs
Tried going down more definitions in the `Cargo.toml`s but basically ran into this issue https://github.com/rust-lang/cargo/issues/1197
Would have included this in a previous PR but thought it needed to be more complex
=> Only reference udisks2 when udev + linux

bb-flasher-sd/src/pal/macos.rs
Not sure about the warnings, but at least this should address the errors
=> macOS: fix clippy errors

Cargo.lock, bb-flasher-sd/Cargo.toml, bb-flasher-sd/src/flashing.rs, bb-flasher-sd/src/pal/windows.rs
After trying out various things, I cannot seem to get windows to reliably
modify anything on SD card after the initial write.
So I am just giving up and modifying the OS image instead before
flashing. This seems to work reasonably well, and is less hacky than
every other thing I have tried.
Fixes #13, #14
=> bb-flasher-sd: Fix windows flashing

Cargo.lock, bb-flasher-sd/Cargo.toml, bb-flasher-sd/README.md, bb-flasher-sd/src/flashing.rs, bb-flasher-sd/src/helpers.rs, bb-flasher-sd/src/lib.rs, bb-flasher/README.md, bb-flasher/src/flasher/sd.rs, bb-flasher/src/lib.rs, bb-imager-cli/src/cli.rs, bb-imager-cli/src/main.rs, bb-imager-gui/src/helpers.rs, bb-imager-gui/src/pages/configuration.rs
- It is better to use SHA verification on passed image rather than doing a sha calculation after reading sd card again.
- Rpi-imager also does not do this kind of verification.
- Also a lot of other cleanup.
=> bb-imager-sd: Remove verify argument

bb-imager-gui/src/helpers.rs, bb-imager-gui/src/ui/flash.rs, iced-loading/src/lib.rs, iced-loading/src/linear.rs
Replace static 50% bar with animated Linear widget for Preparing, Verifying, and Customizing, fixing issue #23.
- Added `Linear` widget in `iced-loading`.
- Updated `flash.rs` to use `Linear` for non-progress states.
- Closes #23.
Changelog: added
https://github.com/user-attachments/assets/608c51af-80b7-40b1-ba2d-a31f8dd54bc7
=> enhancement: Add indeterminate progress bar for non-progress states (#23)

bb-config/src/lib.rs
- Seems much faster than the old distros.json url
=> bb-config: Use github raw URL

bb-flasher-sd/src/customization.rs, bb-flasher/src/flasher/sd.rs, bb-flasher/src/lib.rs, bb-imager-cli/src/cli.rs, bb-imager-cli/src/main.rs, bb-imager-gui/src/helpers.rs, bb-imager-gui/src/persistance.rs, bb-imager-gui/src/ui/configuration.rs
- The sysconfig.txt variable used is `usb_enable_dhcp`
- Defaults to true for new users on windows and macos.
=> Add USB DHCP option to both GUI and CLI

bb-imager-gui/src/helpers.rs, bb-imager-gui/src/message.rs, bb-imager-gui/src/ui/home.rs
Do not show confirmation dialog when no customization options are present.
=> bb-imager-gui: No confirmation dialog for images without customization

bb-imager-gui/src/persistance.rs
- USB DHCP was enabled by default on windows. However, this seems to have stopped working. So just do not enable it by default on Windows.
=> bb-imager-gui: Disable usb-dhcp default on windows

Cargo.lock, bb-imager-gui/Cargo.toml, bb-imager-gui/src/helpers.rs, bb-imager-gui/src/message.rs
- Flatpak prefers xdg portal for notification, so use that.
- Have notify-rust as fallback.
=> bb-imager-gui: Add xdg portal notification

bb-imager-gui/assets/packages/linux/flatpak/org.beagleboard.imagingutility.metainfo.xml
- Fix things flagged by flathub
=> bb-imager-gui: Fix metainfo

Cargo.lock, bb-flasher-sd/Cargo.toml, bb-flasher-sd/src/flashing.rs, bb-flasher-sd/src/pal/linux.rs
- Disable OS cache when writing to SD Card on Linux from GUI. This make the progress bar represent the actual progress.
- Requires buffer to be 512 byte aligned.
- Also make buffer size 1MB for a bit better performance.
- Still no match for Balena Etcher.
=> bb-flasher-sd: linux: Disable OS cache

bb-downloader/src/lib.rs, bb-imager-gui/src/helpers.rs, bb-imager-gui/src/main.rs, bb-imager-gui/src/message.rs, bb-imager-gui/src/persistance.rs
- Log to a file (along with stdout).
- This should make debugging other people's errors easier since they can just send the log files.
=> bb-imager-gui: Log to file

bb-flasher-sd/src/pal/linux.rs
- Seems to cause open to fail on Debian.
- Not sure if related to the Desktop environment or distro. Since I only added it for the sake of it, removing it for now.
=> bb-flasher-sd: Remove O_EXCL flag

bb-imager-gui/src/helpers.rs, bb-imager-gui/src/main.rs, bb-imager-gui/src/ui/configuration.rs
- Show log file path in settings. Allows users to easily identify the log file location.
- Fixes #80
=> bb-imager-gui: Show Log file path

bb-imager-gui/src/main.rs
Ensure that the folder for log file eists
=> bb-imager-gui: Create log dir if does not exist

bb-flasher-sd/src/lib.rs, bb-flasher-sd/src/pal/windows.rs
- It's a single powershell command with no stdin inputs.
- Much faster than using diskpart with Rust process.
- Fixes #91
=> bb-flasher-sd: windows: Use Clear-Disk instead of diskpart

Cargo.lock, bb-downloader/Cargo.toml
- Will fail to compile on windows msvc, so only enable it when target is not windows.
=> bb-downloader: Enable SHA2 ASM

bb-flasher-sd/src/pal/macos.rs
- No idea if it works, but technically I don't see any reason it shouldn't.
- Fixes #24
=> bb-flasher-sd: Add macos format support

assets/os/armbian.png, assets/os/armbian.webp, assets/os/microblocks.svg, assets/os/micropython.webp, assets/os/template.psd, assets/os/zephyr.png, assets/os/zephyr.webp
- Using transparent background.
- Not using lfs for the svgs because they are more text (and less blobby) than a lot of svgs I have seen in the past. So seems like they will do wall being tracked by git.
=> assets: os: Update images

Cargo.lock, bb-downloader/Cargo.toml
- Brings the appsize down a bit.
- More linux friendly for packaging.
=> bb-downloader: Use default features for reqwest
